version: 0.2

phases:
  pre_build:
    commands:
      - cd postgis-server
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - VERSION=$(TZ='Europe/Berlin' date +'%Y-%m-%d_%H-%M-%S')
      - echo "building $VERSION"
      - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:$VERSION .
      - docker tag $IMAGE_NAME:$VERSION $REPOSITORY_URI:$VERSION
      - docker tag $IMAGE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$VERSION
      - docker push $REPOSITORY_URI:$IMAGE_TAG
